[2024-06-16T15:54:37.113+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_ml_to_postgres.load_data manual__2024-06-16T15:51:44.851067+00:00 [queued]>
[2024-06-16T15:54:37.116+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_ml_to_postgres.load_data manual__2024-06-16T15:51:44.851067+00:00 [queued]>
[2024-06-16T15:54:37.116+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-06-16T15:54:37.121+0000] {taskinstance.py:2191} INFO - Executing <Task(RedshiftDataOperator): load_data> on 2024-06-16 15:51:44.851067+00:00
[2024-06-16T15:54:37.124+0000] {standard_task_runner.py:60} INFO - Started process 24323 to run task
[2024-06-16T15:54:37.126+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 's3_to_ml_to_postgres', 'load_data', 'manual__2024-06-16T15:51:44.851067+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/ml_dataset_preparation.py', '--cfg-path', '/tmp/tmp2zlpjxu5']
[2024-06-16T15:54:37.128+0000] {standard_task_runner.py:88} INFO - Job 64: Subtask load_data
[2024-06-16T15:54:37.157+0000] {task_command.py:423} INFO - Running <TaskInstance: s3_to_ml_to_postgres.load_data manual__2024-06-16T15:51:44.851067+00:00 [running]> on host 22dc78ccc862
[2024-06-16T15:54:37.196+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_ml_to_postgres' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T15:51:44.851067+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T15:51:44.851067+00:00'
[2024-06-16T15:54:37.196+0000] {redshift_data.py:122} INFO - Executing statement: 
    COPY transformed_data
    FROM 's3://velib-project/transformed_data.csv'
    IAM_ROLE 'arn:aws:iam::891377001948:role/RedshiftCopyRole'
    FORMAT AS CSV
    IGNOREHEADER 1;
    
[2024-06-16T15:54:37.200+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2024-06-16T15:54:37.200+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-06-16T15:54:37.328+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/operators/redshift_data.py", line 124, in execute
    self.statement_id = self.hook.execute_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 99, in execute_query
    resp = self.conn.execute_statement(**trim_none_values(kwargs))
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 704, in conn
    return self.get_client_type(region_name=self.region_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 674, in get_client_type
    return session.client(
  File "/home/airflow/.local/lib/python3.8/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 161, in create_client
    client_args = self._get_client_args(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _get_client_args
    return args_creator.get_client_args(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/args.py", line 100, in get_client_args
    final_args = self.compute_client_args(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/args.py", line 219, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/args.py", line 369, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/args.py", line 474, in _resolve_endpoint
    return endpoint_bridge.resolve(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 613, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/regions.py", line 229, in construct_endpoint
    result = self._endpoint_for_partition(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/regions.py", line 277, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
[2024-06-16T15:54:37.335+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=s3_to_ml_to_postgres, task_id=load_data, execution_date=20240616T155144, start_date=20240616T155437, end_date=20240616T155437
[2024-06-16T15:54:37.340+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 64 for task load_data (You must specify a region.; 24323)
[2024-06-16T15:54:37.358+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-16T15:54:37.367+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
