[2024-06-14T19:46:29.084+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_ml_to_postgres.setup_create_table manual__2024-06-14T19:45:20.701876+00:00 [queued]>
[2024-06-14T19:46:29.087+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_ml_to_postgres.setup_create_table manual__2024-06-14T19:45:20.701876+00:00 [queued]>
[2024-06-14T19:46:29.088+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-06-14T19:46:29.092+0000] {taskinstance.py:2191} INFO - Executing <Task(RedshiftDataOperator): setup_create_table> on 2024-06-14 19:45:20.701876+00:00
[2024-06-14T19:46:29.095+0000] {standard_task_runner.py:60} INFO - Started process 1780 to run task
[2024-06-14T19:46:29.097+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 's3_to_ml_to_postgres', 'setup_create_table', 'manual__2024-06-14T19:45:20.701876+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/ml_dataset_preparation.py', '--cfg-path', '/tmp/tmpe2ixzwab']
[2024-06-14T19:46:29.098+0000] {standard_task_runner.py:88} INFO - Job 41: Subtask setup_create_table
[2024-06-14T19:46:29.116+0000] {task_command.py:423} INFO - Running <TaskInstance: s3_to_ml_to_postgres.setup_create_table manual__2024-06-14T19:45:20.701876+00:00 [running]> on host 22dc78ccc862
[2024-06-14T19:46:29.143+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_ml_to_postgres' AIRFLOW_CTX_TASK_ID='setup_create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T19:45:20.701876+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T19:45:20.701876+00:00'
[2024-06-14T19:46:29.144+0000] {redshift_data.py:122} INFO - Executing statement: 
DROP TABLE IF EXISTS transformed_data;
CREATE TABLE transformed_data(
'stationcode',
'name',
'is_installed',
'capacity',
'numdocksavailable',
'numbikesavailable',
'mechanical',
'ebike',
'is_renting',
'is_returning',
'nom_arrondissement_communes',
'code_insee_commune',
'longitude', 
'latitude', 
'date', 
'year', 
'month', 
'day', 
'time');
    
[2024-06-14T19:46:29.147+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2024-06-14T19:46:29.147+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-06-14T19:46:29.919+0000] {redshift_data.py:113} INFO - Polling statement df7ca7fc-92da-4baf-b6f3-247b1feccbc5
[2024-06-14T19:46:29.993+0000] {redshift_data.py:129} INFO - Query PICKED
[2024-06-14T19:46:40.034+0000] {redshift_data.py:113} INFO - Polling statement df7ca7fc-92da-4baf-b6f3-247b1feccbc5
[2024-06-14T19:46:40.269+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/operators/redshift_data.py", line 124, in execute
    self.statement_id = self.hook.execute_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 107, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 124, in wait_for_results
    raise ValueError(
ValueError: Statement 'df7ca7fc-92da-4baf-b6f3-247b1feccbc5' terminated with status FAILED. Response details: {'CreatedAt': datetime.datetime(2024, 6, 14, 19, 46, 29, 724000, tzinfo=tzlocal()),
 'Database': 'dev',
 'DbUser': 'IAM:velib_project',
 'Duration': -1,
 'Error': 'ERROR: syntax error at or near "\'stationcode\'"\n  Position: 33',
 'HasResultSet': False,
 'Id': 'df7ca7fc-92da-4baf-b6f3-247b1feccbc5',
 'QueryString': '\n'
                'DROP TABLE IF EXISTS transformed_data;\n'
                'CREATE TABLE transformed_data(\n'
                "'stationcode',\n"
                "'name',\n"
                "'is_installed',\n"
                "'capacity',\n"
                "'numdocksavailable',\n"
                "'numbikesavailable',\n"
                "'mechanical',\n"
                "'ebike',\n"
                "'is_renting',\n"
                "'is_returning',\n"
                "'nom_arrondissement_communes',\n"
                "'code_insee_commune',\n"
                "'longitude', \n"
                "'latitude', \n"
                "'date', \n"
                "'year', \n"
                "'month', \n"
                "'day', \n"
                "'time');\n"
                '    ',
 'RedshiftPid': 1073807580,
 'RedshiftQueryId': 0,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '772',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Fri, 14 Jun 2024 19:46:39 GMT',
                                      'x-amzn-requestid': '72f67d86-f193-4432-a822-d3e163b44606'},
                      'HTTPStatusCode': 200,
                      'RequestId': '72f67d86-f193-4432-a822-d3e163b44606',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2024, 6, 14, 19, 46, 30, 343000, tzinfo=tzlocal()),
 'WorkgroupName': 'redshift-velib'}
[2024-06-14T19:46:40.273+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=s3_to_ml_to_postgres, task_id=setup_create_table, execution_date=20240614T194520, start_date=20240614T194629, end_date=20240614T194640
[2024-06-14T19:46:40.282+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 41 for task setup_create_table (Statement 'df7ca7fc-92da-4baf-b6f3-247b1feccbc5' terminated with status FAILED. Response details: {'CreatedAt': datetime.datetime(2024, 6, 14, 19, 46, 29, 724000, tzinfo=tzlocal()),
 'Database': 'dev',
 'DbUser': 'IAM:velib_project',
 'Duration': -1,
 'Error': 'ERROR: syntax error at or near "\'stationcode\'"\n  Position: 33',
 'HasResultSet': False,
 'Id': 'df7ca7fc-92da-4baf-b6f3-247b1feccbc5',
 'QueryString': '\n'
                'DROP TABLE IF EXISTS transformed_data;\n'
                'CREATE TABLE transformed_data(\n'
                "'stationcode',\n"
                "'name',\n"
                "'is_installed',\n"
                "'capacity',\n"
                "'numdocksavailable',\n"
                "'numbikesavailable',\n"
                "'mechanical',\n"
                "'ebike',\n"
                "'is_renting',\n"
                "'is_returning',\n"
                "'nom_arrondissement_communes',\n"
                "'code_insee_commune',\n"
                "'longitude', \n"
                "'latitude', \n"
                "'date', \n"
                "'year', \n"
                "'month', \n"
                "'day', \n"
                "'time');\n"
                '    ',
 'RedshiftPid': 1073807580,
 'RedshiftQueryId': 0,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '772',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Fri, 14 Jun 2024 19:46:39 GMT',
                                      'x-amzn-requestid': '72f67d86-f193-4432-a822-d3e163b44606'},
                      'HTTPStatusCode': 200,
                      'RequestId': '72f67d86-f193-4432-a822-d3e163b44606',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2024, 6, 14, 19, 46, 30, 343000, tzinfo=tzlocal()),
 'WorkgroupName': 'redshift-velib'}; 1780)
[2024-06-14T19:46:40.314+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-14T19:46:40.324+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
