[2024-06-16T18:39:13.256+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: s3_to_ml_to_postgres.transform_data manual__2024-06-16T18:37:27.958991+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
